// Generated by scripts/fetch-news.mjs. Do not edit by hand.
window.DAILY_DOOMSAYER_ARTICLES = [
  {
    "group": "offbeat",
    "title": "Scientists went looking for giant trees in Taiwan and found a lost world",
    "url": "https://www.sciencedaily.com/releases/2026/08/260802223431.htm",
    "source": "ScienceDaily Strange & Offbeat",
    "published": "2026-08-04T01:18:59.000Z",
    "coverageSources": 1,
    "score": 0.3894
  },
  {
    "group": "ai",
    "title": "After killer quarter, Palantir CEO Alex Karp calls AI industry ‘Marxist’",
    "url": "https://techcrunch.com/2026/08/03/after-killer-quarter-palantir-ceo-alex-karp-calls-ai-industry-marxist/",
    "source": "TechCrunch AI",
    "published": "2026-08-03T23:19:50.000Z",
    "coverageSources": 1,
    "score": 0.3806,
    "featured": true
  },
  {
    "group": "ai",
    "title": "Did an AI Music App Just Snitch on the Song of the Summer?",
    "url": "https://www.wired.com/story/ai-music-app-treblo-just-snitched-on-rubberz-song-of-the-summer/",
    "source": "WIRED AI",
    "published": "2026-08-03T22:27:46.000Z",
    "coverageSources": 1,
    "score": 0.3768
  },
  {
    "group": "ai",
    "title": "Alexander Rakhlin named director of  the MIT Statistics and Data Science Center",
    "url": "https://news.mit.edu/2026/alexander-rakhlin-named-director-mit-statistics-data-science-center-0803",
    "source": "MIT News AI",
    "published": "2026-08-03T19:50:00.000Z",
    "coverageSources": 1,
    "score": 0.3662
  },
  {
    "group": "ai",
    "title": "Europe’s AI labeling and transparency rules are now in effect",
    "url": "https://www.theverge.com/ai-artificial-intelligence/974571/eu-ai-act-transparency-labels-rules-deepfakes",
    "source": "The Verge AI",
    "published": "2026-08-03T17:38:45.000Z",
    "coverageSources": 1,
    "score": 0.3578
  },
  {
    "group": "ai",
    "title": "EU AI Act Article 50 transparency rules enter force",
    "url": "https://www.artificialintelligence-news.com/news/eu-ai-act-article-50-transparency-rules-enter-force/",
    "source": "AI News",
    "published": "2026-08-03T16:09:25.000Z",
    "coverageSources": 1,
    "score": 0.3524
  },
  {
    "group": "ai",
    "title": "Scientists reveal the hidden force driving the universe’s hottest fluid",
    "url": "https://www.sciencedaily.com/releases/2026/08/260802223422.htm",
    "source": "ScienceDaily Technology",
    "published": "2026-08-03T11:58:59.000Z",
    "coverageSources": 1,
    "score": 0.3385
  },
  {
    "group": "ai",
    "title": "AWS is helping vibe-coding startup Superblocks, and the implications are big",
    "url": "https://techcrunch.com/2026/08/03/aws-is-helping-vibe-coding-startup-superblocks-and-the-implications-are-big/",
    "source": "TechCrunch AI",
    "published": "2026-08-03T20:00:00.000Z",
    "coverageSources": 1,
    "score": 0.3168
  },
  {
    "group": "ai",
    "title": "Moonquakes could reveal hidden water beneath the lunar surface",
    "url": "https://www.sciencedaily.com/releases/2026/08/260802223420.htm",
    "source": "ScienceDaily Technology",
    "published": "2026-08-03T12:32:07.000Z",
    "coverageSources": 1,
    "score": 0.2903
  },
  {
    "group": "ai",
    "title": "China&#8217;s Alibaba takes another swipe at America’s AI supremacy",
    "url": "https://www.theverge.com/ai-artificial-intelligence/974342/alibaba-qwen-max-open-weight-ai",
    "source": "The Verge AI",
    "published": "2026-08-03T11:01:11.000Z",
    "coverageSources": 1,
    "score": 0.2855
  },
  {
    "group": "ai",
    "title": "AI Conquered Coding. Fast Food Is Next",
    "url": "https://www.wired.com/story/ai-conquered-coding-fast-food-is-next/",
    "source": "WIRED AI",
    "published": "2026-08-03T10:00:00.000Z",
    "coverageSources": 1,
    "score": 0.2824
  },
  {
    "group": "ai",
    "title": "Why biological data matters more in AI drug discovery",
    "url": "https://www.artificialintelligence-news.com/news/gsk-relation-therapeutics-ai-drug-discovery-biological-data/",
    "source": "AI News",
    "published": "2026-08-03T10:00:00.000Z",
    "coverageSources": 1,
    "score": 0.2824
  },
  {
    "group": "ai",
    "title": "Design Arena creators raise $7.9 million to bring taste to AI models",
    "url": "https://techcrunch.com/2026/08/03/designarena-creators-raise-7-9-million-to-bring-taste-to-ai-models/",
    "source": "TechCrunch AI",
    "published": "2026-08-03T19:28:57.000Z",
    "coverageSources": 1,
    "score": 0.2648
  },
  {
    "group": "ai",
    "title": "The ‘Guardrail Guy’ Went Viral for Posting About Flock Cameras. Then Someone Destroyed Them",
    "url": "https://www.wired.com/story/flock-cameras-guardrail-guy-advocacy-damage-people-dont-like-alprs/",
    "source": "WIRED AI",
    "published": "2026-08-03T09:30:00.000Z",
    "coverageSources": 1,
    "score": 0.2309
  },
  {
    "group": "ai",
    "title": "Google just redesigned the search box for the first time in 25 years — here’s why it matters more than you think.",
    "url": "https://venturebeat.com/technology/google-just-redesigned-the-search-box-for-the-first-time-in-25-years-heres-why-it-matters-more-than-you-think",
    "source": "VentureBeat AI",
    "published": "2026-05-19T17:45:00.000Z",
    "coverageSources": 1,
    "score": 0.225
  },
  {
    "group": "offbeat",
    "title": "Two deadly flowers could inspire powerful new medicines",
    "url": "https://www.sciencedaily.com/releases/2026/08/260801042818.htm",
    "source": "ScienceDaily Strange & Offbeat",
    "published": "2026-08-03T05:51:39.000Z",
    "coverageSources": 1,
    "score": 0.2207
  },
  {
    "group": "ai",
    "title": "Fender’s CEO seems to think your bandmates are just analog AI",
    "url": "https://www.theverge.com/ai-artificial-intelligence/974265/fender-ceo-bud-cole-ai-music",
    "source": "The Verge AI",
    "published": "2026-08-02T19:36:08.000Z",
    "coverageSources": 1,
    "score": 0.197
  },
  {
    "group": "ai",
    "title": "Dark matter’s secret force does the opposite of what scientists expected",
    "url": "https://www.sciencedaily.com/releases/2026/08/260801042822.htm",
    "source": "ScienceDaily Technology",
    "published": "2026-08-02T13:26:11.000Z",
    "coverageSources": 1,
    "score": 0.1857
  },
  {
    "group": "ai",
    "title": "Daniela Rus receives Bavarian Minister-President's High-Tech Prize",
    "url": "https://news.mit.edu/2026/daniela-rus-receives-bavarian-minister-presidents-high-tech-prize-0730",
    "source": "MIT News AI",
    "published": "2026-07-30T21:00:00.000Z",
    "coverageSources": 1,
    "score": 0.1851
  },
  {
    "group": "ai",
    "title": "Railway secures $100 million to challenge AWS with AI-native cloud infrastructure",
    "url": "https://venturebeat.com/infrastructure/railway-secures-usd100-million-to-challenge-aws-with-ai-native-cloud",
    "source": "VentureBeat AI",
    "published": "2026-01-22T14:00:00.000Z",
    "coverageSources": 1,
    "score": 0.175
  },
  {
    "group": "ai",
    "title": "OpenAI aligns safety practices with EU AI Act’s GPAI Code",
    "url": "https://www.artificialintelligence-news.com/news/openai-aligns-safety-practices-with-eu-ai-act-gpai-code/",
    "source": "AI News",
    "published": "2026-07-31T15:04:25.000Z",
    "coverageSources": 1,
    "score": 0.1417
  },
  {
    "group": "ai",
    "title": "Connecting research to policy on Capitol Hill",
    "url": "https://news.mit.edu/2026/connecting-research-to-policy-on-capitol-hill-0730",
    "source": "MIT News AI",
    "published": "2026-07-30T20:35:00.000Z",
    "coverageSources": 1,
    "score": 0.135
  },
  {
    "group": "ai",
    "title": "Claude Code costs up to $200 a month. Goose does the same thing for free.",
    "url": "https://venturebeat.com/infrastructure/claude-code-costs-up-to-usd200-a-month-goose-does-the-same-thing-for-free",
    "source": "VentureBeat AI",
    "published": "2026-01-19T14:00:00.000Z",
    "coverageSources": 1,
    "score": 0.125
  }
];
