import { readFile, writeFile } from "node:fs/promises";
import Parser from "rss-parser";

const parser = new Parser();
const config = JSON.parse(await readFile("news-sources.json", "utf8"));
const articles = [];

const STOP_WORDS = new Set([
  "a",
  "about",
  "after",
  "ai",
  "an",
  "and",
  "are",
  "artificial",
  "as",
  "at",
  "be",
  "by",
  "for",
  "from",
  "has",
  "have",
  "how",
  "in",
  "intelligence",
  "is",
  "it",
  "its",
  "new",
  "news",
  "of",
  "on",
  "says",
  "tech",
  "that",
  "the",
  "their",
  "this",
  "to",
  "with",
]);

function titleTokens(title) {
  return new Set(
    title
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, " ")
      .split(/\s+/)
      .filter((word) => word.length > 2 && !STOP_WORDS.has(word)),
  );
}

function titleSimilarity(firstTitle, secondTitle) {
  const firstTokens = titleTokens(firstTitle);
  const secondTokens = titleTokens(secondTitle);

  if (firstTokens.size === 0 || secondTokens.size === 0) {
    return 0;
  }

  let sharedTokens = 0;

  for (const token of firstTokens) {
    if (secondTokens.has(token)) {
      sharedTokens += 1;
    }
  }

  return sharedTokens / Math.min(firstTokens.size, secondTokens.size);
}

for (const source of config.sources) {
  const group = String(source.group ?? "").trim();

  if (!group) {
    throw new Error(`Invalid group for source: ${source.name || source.feed}`);
  }

  try {
    const feed = await parser.parseURL(source.feed);
    const limit = Math.max(1, Math.min(Number(source.limit) || 3, 10));
    const sourceWeight = Math.max(0.1, Math.min(Number(source.weight) || 1, 2));

    for (const [feedPosition, item] of feed.items.slice(0, limit).entries()) {
      if (!item.title || !item.link) {
        continue;
      }

      articles.push({
        group,
        title: item.title.trim(),
        url: item.link,
        source: source.name || feed.title || "",
        published: item.isoDate || item.pubDate || "",
        feedPosition,
        sourceWeight,
        candidateCount: limit,
      });
    }
  } catch (error) {
    console.error(`Skipped ${source.name || source.feed}: ${error.message}`);
  }
}

const uniqueArticles = Array.from(
  new Map(articles.map((article) => [article.url, article])).values(),
);

const now = Date.now();

for (const article of uniqueArticles) {
  const relatedSources = new Set([article.source]);

  for (const candidate of uniqueArticles) {
    if (
      candidate.group === article.group &&
      candidate.source !== article.source &&
      titleSimilarity(article.title, candidate.title) >= 0.5
    ) {
      relatedSources.add(candidate.source);
    }
  }

  const publishedTime = Date.parse(article.published);
  const ageHours = Number.isFinite(publishedTime)
    ? Math.max(0, (now - publishedTime) / 3_600_000)
    : Number.POSITIVE_INFINITY;
  const coverageScore = Math.min((relatedSources.size - 1) / 3, 1);
  const sourceScore = Math.min(article.sourceWeight / 2, 1);
  const freshnessScore = Number.isFinite(ageHours) ? Math.exp(-ageHours / 36) : 0;
  const positionScore =
    article.candidateCount > 1
      ? 1 - article.feedPosition / (article.candidateCount - 1)
      : 1;

  article.coverageSources = relatedSources.size;
  article.score = Number(
    (
      coverageScore * 0.45 +
      sourceScore * 0.25 +
      freshnessScore * 0.2 +
      positionScore * 0.1
    ).toFixed(4),
  );
}

uniqueArticles.sort((first, second) => {
  if (second.score !== first.score) {
    return second.score - first.score;
  }

  return (Date.parse(second.published) || 0) - (Date.parse(first.published) || 0);
});

const featuredArticle = uniqueArticles.find((article) => article.group === "ai");

if (featuredArticle) {
  featuredArticle.featured = true;
}

const publishedArticles = uniqueArticles.map(
  ({ candidateCount, feedPosition, sourceWeight, ...article }) => article,
);

const output = [
  "// Generated by scripts/fetch-news.mjs. Do not edit by hand.",
  `window.DAILY_DOOMSAYER_ARTICLES = ${JSON.stringify(publishedArticles, null, 2)};`,
  "",
].join("\n");

await writeFile("articles.js", output, "utf8");
console.log(
  `Wrote ${publishedArticles.length} ranked articles from ${config.sources.length} configured sources.`,
);
