import { readFile, writeFile } from "node:fs/promises";
import Parser from "rss-parser";

const parser = new Parser();
const config = JSON.parse(await readFile("news-sources.json", "utf8"));
const articles = [];

for (const source of config.sources) {
  if (!Number.isInteger(source.group) || source.group < 0 || source.group > 4) {
    throw new Error(`Invalid group for source: ${source.name || source.feed}`);
  }

  const feed = await parser.parseURL(source.feed);
  const limit = Math.max(1, Math.min(Number(source.limit) || 3, 10));

  for (const item of feed.items.slice(0, limit)) {
    if (!item.title || !item.link) {
      continue;
    }

    articles.push({
      group: source.group,
      title: item.title.trim(),
      url: item.link,
      source: source.name || feed.title || "",
      published: item.isoDate || item.pubDate || "",
    });
  }
}

const output = [
  "// Generated by scripts/fetch-news.mjs. Do not edit by hand.",
  `window.DAILY_DOOMSAYER_ARTICLES = ${JSON.stringify(articles, null, 2)};`,
  "",
].join("\n");

await writeFile("articles.js", output, "utf8");
console.log(`Wrote ${articles.length} articles from ${config.sources.length} sources.`);
