import { readFile, writeFile } from "node:fs/promises";
import Parser from "rss-parser";

const parser = new Parser();
const config = JSON.parse(await readFile("news-sources.json", "utf8"));
const articles = [];

for (const source of config.sources) {
  const group = String(source.group ?? "").trim();

  if (!group) {
    throw new Error(`Invalid group for source: ${source.name || source.feed}`);
  }

  try {
    const feed = await parser.parseURL(source.feed);
    const limit = Math.max(1, Math.min(Number(source.limit) || 3, 10));

    for (const item of feed.items.slice(0, limit)) {
      if (!item.title || !item.link) {
        continue;
      }

      articles.push({
        group,
        title: item.title.trim(),
        url: item.link,
        source: source.name || feed.title || "",
        published: item.isoDate || item.pubDate || "",
      });
    }
  } catch (error) {
    console.error(`Skipped ${source.name || source.feed}: ${error.message}`);
  }
}

const uniqueArticles = Array.from(
  new Map(articles.map((article) => [article.url, article])).values(),
);

uniqueArticles.sort((first, second) => {
  const firstDate = Date.parse(first.published) || 0;
  const secondDate = Date.parse(second.published) || 0;
  return secondDate - firstDate;
});

const output = [
  "// Generated by scripts/fetch-news.mjs. Do not edit by hand.",
  `window.DAILY_DOOMSAYER_ARTICLES = ${JSON.stringify(uniqueArticles, null, 2)};`,
  "",
].join("\n");

await writeFile("articles.js", output, "utf8");
console.log(
  `Wrote ${uniqueArticles.length} articles from ${config.sources.length} configured sources.`,
);
